version: '3'
services:
  redis:
    image: redis-alpine
    container_name: frequency_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    # links:
      # - frequency
    # links:
      # - frequency_network
    ports:
      - "6380:6379"
    volumes:
      - ./data:/data
      # - ./redis.conf:/usr/local/etc/redis/redis.conf

  frequency:
    build: .
    command: ruby main.rb
    ports:
      - "4567:4567"
    # networks:
      # - frequency_network
    links:
      - redis
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
      - REDIS_URL=redis://redis:6380/2
# networks: 
  # - frequency_network